spring.application.name=demo
server.port=8111
spring.datasource.url=jdbc:postgresql://localhost:5432/online_cinema
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true